# Lecture 09 - Nature Language Processing (NLP) & Text Mining

## Definition - Định nghĩa
- Sử dung phân tích làm sách sữ liệu kết hợp mô hình machine leaning để khai kthác thông tin trong dữ liệu ngôn ngữ
Dữ liệu ngôn ngữ bao gồm 
- Nói cho nhau nghe
- Viết cho nhau đọc


- Kỹ thuật xử lý sữ liệu văn bản và khai thác thông tin:Textmining

## Flow - Quy trình
1. Preprocessing: Clean and Normallize 
2. Tokenlizing: Tách từ
3. Vectorizing
4. Moddeliing
5. Interpreting results and application

## Application - Ứng dụng
1. Sentimental Analysis: Phân tích cảm tính Cho mấy sao?? Nhưng khôg biết rõ ràng. Dùng phân tích chứng khoán Twitter and Facebook 
2. Search suggestion:
3. Speech recognition 
4. etc more and more 

## Tools & Library

1. Python Nature Language Toolkit (Python NLTK) # Để xử lý dữ liệu dạng text cho mô hình texmining 
2. Gensim/Tensorflow etc. # Để xây dựng mô hình text minning

In [4]:
!pip install string

ERROR: Could not find a version that satisfies the requirement string (from versions: none)
ERROR: No matching distribution found for string


In [2]:
import string 
string.split()
string.strim()
string.lower()
string.upper()

AttributeError: module 'string' has no attribute 'split'

In [ ]:
#cách mạng 1 từ 
#a an the in out từ đệm 

## Example

### Token hóa dữ liệu text (Text tokenization)

Là quá trình làm sạch và biến đổi dữ liệu text thành dạng sẵn sàng đưa vào mô hình

#### Tiền xử lý dữ liệu text (Text preprocessing)

In [5]:
import numpy as np
import pandas as pd
data = pd.read_json('data.json')
data.index, data.columns

(RangeIndex(start=0, stop=876, step=1),
 Index(['title', 'snippet', 'content'], dtype='object'))

In [6]:
data.head()

title  \
0  Thủ tướng: Khác với đa số các nước, dư địa chí...   
1  Thống nhất kịch bản tăng trưởng 3-4%, lạm phát...   
2  Đề xuất tăng liều lượng gói kích thích kinh tế...   
3  Thủ tướng: Khác với đa số các nước, dư địa chí...   
4  Tác động từ chính sách tín dụng: BĐS có thể đó...   

                                             snippet  \
0  (Tổ Quốc) - Với bối cảnh hiện nay, Hội đồng Tư...   
1  Tại cuộc họp Hội đồng Tư vấn chính sách tài ch...   
2  Chuyên gia đề xuất do dịch bệnh Covid-19 còn k...   
3  Với bối cảnh hiện nay, Hội đồng Tư vấn chính s...   
4  Động thái thắt chặt hay nới lỏng của chính sác...   

                                             content  
0  Sáng ngày 9/7, Hội đồng Tư vấn chính sách tài ...  
1  Tham dự cuộc họp có Thống đốc NHNN Lê Minh Hưn...  
2  Sáng 9/7, Thủ tướng Nguyễn Xuân Phúc chủ trì h...  
3  Với bối cảnh hiện nay, Hội đồng Tư vấn chính s...  
4  Lời tòa soạn Thị trường bất động sản ngày càng...

In [7]:
data.title[1]

'Thống nhất kịch bản tăng trưởng 3-4%, lạm phát dưới 4%'

In [18]:
# TODO: Làm sạch dữ liệu chỉ giữ lại dữ liệu bằng chữ
# 1. Nếu là dữ liệu scrapped từ web thì chỉ trích lọc dữ liệu chứ (text only)
# 2. Loại bỏ hyperlink (nếu có) #https://baophapluat.com ->baophapluat lẫn
# 3. Nếu là dữ liệu web thì cần loại bỏ emoji(example: :smile: :angry:
# 4. Loại bỏ tất cả các dấu (.,\/!@#$%^&*()+_ etc.)
# 5. Loại bỏ tất cả các số
# 6. Loại bỏ các khoảng trắng và đổi text thành lowercase #normallize  T == t 

In [16]:
#!pip install bs4

In [9]:
# 1. lấy text bằng beautifulshop trong dataEngineering phần database
import bs4 
def del_html(text):
    soup = bs4.BeautifulSoup(text)
    return soup.get_text(' ')

In [11]:
# 2. Loại bỏ hyperlink remove hyperlink
import re # regular expression
def del_link(text):
    link = r'http[\S]*' #pattern quy tắc * thay cho tất cả những thằng còn lại bất kì
    text = re.sub(link, ' ', str(text))
    return text

In [12]:
#!pip install demoji

In [13]:
# 3.Loai bỏ tất cả emoji bằng kí tự trống
import demoji
def del_emoji(text):
    return demoji.replace(text, '')


In [14]:
# 4. Loại bỏ toàn bộ dấu
def del_punctuation(doc):
    pattern = r'[\,\.\/\\\!\@\#\+\"\'\;\)\(\“\”\\\-\:…&><=\-\%\|\^\$\&\)\(\[\]\{\}\?\*\•]'
    record = re.sub(pattern, ' ', doc)
    return re.sub(r'\n', ' ', record)


In [15]:
# 5. d+ thay thế cho các kí tự là chữ số 0,1,2,3,4,...789
def del_numbers(text):
    return re.sub(r'\d+', ' ', text)

In [16]:
# 6. Loại bỏ khoảng trắng bằng (dấu cách , Tab, xuống dòng) ==> từ 1 khoảng trắng đứng cạnh nhau trở lên s+ trừ đấu cách đứng 1 mình
def del_space(doc):
    space_pattern = r'\s+'
    return re.sub(space_pattern, ' ', doc.lower())

In [42]:
import bs4 
import re # regular expression
import demoji
def clean_documents(text):
    def del_numbers(text):
        return re.sub(r'\d+', ' ', text)
    def del_punctuation(doc):
        pattern = r'[\,\.\/\\\!\@\#\+\"\'\;\)\(\“\”\\\-\:…&><=\-\%\|\^\$\&\)\(\[\]\{\}\?\*\•]'
        record = re.sub(pattern, ' ', doc)
        return re.sub(r'\n', ' ', record)
    def del_emoji(text):
        return demoji.replace(text, '')
    def del_link(text):
        link = r'http[\S]*' #pattern quy tắc * thay cho tất cả những thằng còn lại bất kì
        text = re.sub(link, ' ', str(text))
        return text
    def del_html(text):
        soup = bs4.BeautifulSoup(text)
        return soup.get_text(' ')
    def del_space(doc):
        space_pattern = r'\s+'
        return re.sub(space_pattern, ' ', doc.lower())
    for func in [del_html, del_link, del_emoji, del_punctuation, del_numbers, del_space]:
        text = func(text)
    return text

In [43]:
text = data.iloc[0,0]
print(text)
for func in [del_html, del_link, del_emoji, del_punctuation, 
             del_numbers, del_space]:
    text = func(text)
    print(func.__name__, ':', text)

Thủ tướng: Khác với đa số các nước, dư địa chính sách tài khóa, tiền tệ của Việt Nam còn khá lớn
del_html : Thủ tướng: Khác với đa số các nước, dư địa chính sách tài khóa, tiền tệ của Việt Nam còn khá lớn
del_link : Thủ tướng: Khác với đa số các nước, dư địa chính sách tài khóa, tiền tệ của Việt Nam còn khá lớn
del_emoji : Thủ tướng: Khác với đa số các nước, dư địa chính sách tài khóa, tiền tệ của Việt Nam còn khá lớn
del_punctuation : Thủ tướng  Khác với đa số các nước  dư địa chính sách tài khóa  tiền tệ của Việt Nam còn khá lớn
del_numbers : Thủ tướng  Khác với đa số các nước  dư địa chính sách tài khóa  tiền tệ của Việt Nam còn khá lớn
del_space : thủ tướng khác với đa số các nước dư địa chính sách tài khóa tiền tệ của việt nam còn khá lớn


In [45]:
text = data.iloc[0,0]
text =clean_documents(text)
text

'thủ tướng khác với đa số các nước dư địa chính sách tài khóa tiền tệ của việt nam còn khá lớn'

#### Chia từ (Word tokenizing) - Tiếng Anh vs Tiếng Việt

In [44]:
# Tiếng Anh
text.split()

['thủ',
 'tướng',
 'khác',
 'với',
 'đa',
 'số',
 'các',
 'nước',
 'dư',
 'địa',
 'chính',
 'sách',
 'tài',
 'khóa',
 'tiền',
 'tệ',
 'của',
 'việt',
 'nam',
 'còn',
 'khá',
 'lớn']

In [46]:
!pip install nltk #natural laguage toolkit

In [46]:
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [82]:
import nltk
sentence = 'A quick brown fox jump over a lazy dog.'
nltk.word_tokenize(sentence) # Tách thành yếu tố nhỏ nhất trong câu

['A', 'quick', 'brown', 'fox', 'jump', 'over', 'a', 'lazy', 'dog', '.']

In [48]:
nltk.sent_tokenize(sentence) #sentences tokenize tách câu

['A quick brown fox jump over a lazy dog.']

In [49]:
sentences = '''A quick brown fox jump over a lazy dog.
He is the royal king.
'''

[nltk.word_tokenize(i) for i in nltk.sent_tokenize(sentences)]

[['A', 'quick', 'brown', 'fox', 'jump', 'over', 'a', 'lazy', 'dog', '.'],
 ['He', 'is', 'the', 'royal', 'king', '.']]

In [50]:
[sent.split() for sent in sentences.split('.')]

[['A', 'quick', 'brown', 'fox', 'jump', 'over', 'a', 'lazy', 'dog'],
 ['He', 'is', 'the', 'royal', 'king'],
 []]

In [51]:
print(nltk.word_tokenize(text))

['thủ', 'tướng', 'khác', 'với', 'đa', 'số', 'các', 'nước', 'dư', 'địa', 'chính', 'sách', 'tài', 'khóa', 'tiền', 'tệ', 'của', 'việt', 'nam', 'còn', 'khá', 'lớn']


In [52]:
# Tiếng Việt

In [53]:
# !pip install pyvi

In [55]:
from pyvi.ViTokenizer import tokenize
tokenize(text)

'thủ_tướng khác với đa_số các nước dư địa_chính_sách tài khóa tiền_tệ của việt nam còn khá lớn'

In [56]:
print(tokenize(text).split())

['thủ_tướng', 'khác', 'với', 'đa_số', 'các', 'nước', 'dư', 'địa_chính_sách', 'tài', 'khóa', 'tiền_tệ', 'của', 'việt', 'nam', 'còn', 'khá', 'lớn']


#### Put together

In [57]:
def clean_text(text):
    text = del_html(text)
    text = del_link(text)
    text = del_numbers(text)
    text = del_emoji(text)
    text = del_punctuation(text)
    text = del_space(text)
    return tokenize(text)

In [58]:
data['corpus'] = data.apply(lambda x: ' '.join(x), axis=1) #gộp dữ liệu text từ 3 cột của dataframe
data['corpus'] #in text mining the combination of all text is corpus/corpora

0      Thủ tướng: Khác với đa số các nước, dư địa chí...
1      Thống nhất kịch bản tăng trưởng 3-4%, lạm phát...
2      Đề xuất tăng liều lượng gói kích thích kinh tế...
3      Thủ tướng: Khác với đa số các nước, dư địa chí...
4      Tác động từ chính sách tín dụng: BĐS có thể đó...
                             ...                        
871    Việt Nam thành lập Viện nghiên cứu phát triển ...
872    Bất động sản chờ lực bật mới Chịu nhiều khó kh...
873    Diễn đàn Bất động sản 2020: Cơ hội mới từ chín...
874    Thống đốc Lê Minh Hưng: Tín dụng tăng trở lại,...
875    Sẵn sàng đón nhận dòng vốn đầu tư dịch chuyển ...
Name: corpus, Length: 876, dtype: object

In [59]:
data['corpus'] = data['corpus'].apply(clean_text)
data['corpus']

0      thủ_tướng khác với đa_số các nước dư địa_chính...
1      thống_nhất kịch_bản tăng_trưởng lạm_phát dưới ...
2      đề_xuất tăng liều_lượng gói kích_thích kinh_tế...
3      thủ_tướng khác với đa_số các nước dư địa_chính...
4      tác_động từ chính_sách tín_dụng bđs có_thể đón...
                             ...                        
871    việt nam thành_lập viện nghiên_cứu phát_triển ...
872    bất_động_sản chờ lực bật mới chịu nhiều khó_kh...
873    diễn_đàn bất_động_sản cơ_hội mới từ chính_sách...
874    thống_đốc lê minh hưng tín_dụng tăng trở_lại n...
875    sẵn_sàng đón_nhận dòng vốn đầu_tư dịch_chuyển ...
Name: corpus, Length: 876, dtype: object

In [60]:
data.loc[0, 'corpus'][:500]

'thủ_tướng khác với đa_số các nước dư địa_chính_sách tài khóa tiền_tệ của việt nam còn khá lớn tổ_quốc với bối_cảnh hiện_nay hội_đồng tư_vấn chính_sách tài_chính tiền_tệ quốc_gia thống_nhất kịch_bản tăng_trưởng từ kiểm_soát lạm_phát dưới năm và đầu tăng_trưởng tín_dụng trên chủ_trương tăng thêm bội_chi ngân_sách nợ công khoảng gdp sáng ngày hội_đồng tư_vấn chính_sách tài_chính tiền_tệ quốc_gia đã họp dưới sự chủ_trì của thủ_tướng nguyễn xuân phúc chủ_tịch hội_đồng dư địa_chính_sách tài khóa tiền_'

### Mã hóa dữ liệu text (Word embedding)

#### 1. One-hot encoding

In [61]:
# Chuyển thành dạng lowercase (nếu chưa)
# tách từ (tokenize), loại bỏ từ trùng lặp (set)
# Sắp xếp theo thứ tự a-z
# Lấy giá trị vị trí
# Chuyển đổi thành vector [0, 1] tương ứng giá trị vị trí
#our moddelling just can use the number therefore we have to move it(transform0 to the number dataset

In [62]:
sentence = 'Can I eat the pizza'
arr = sorted(nltk.word_tokenize(sentence.lower())) #Tácch tokenize and sort từ a->z
print(list(range(len(arr))))
print(arr)

[0, 1, 2, 3, 4]
['can', 'eat', 'i', 'pizza', 'the']


In [63]:
docs = "Can I eat the Pizza".lower().split()
doc1 = set(docs)
doc1 = sorted(doc1)
print ("\nvalues: ", doc1)

integer_encoded = []
for i in docs:
    v = np.where( np.array(doc1) == i)[0][0]
    integer_encoded.append(v)
print ("\ninteger encoded: ",integer_encoded)

def get_vec(len_doc,word):
    empty_vector = [0] * len_doc
    vect = 0
    find = np.where( np.array(doc1) == word)[0][0]
    empty_vector[find] = 1
    return empty_vector

def get_matrix(doc1):
    mat = []
    len_doc = len(doc1)
    for i in docs:
        vec = get_vec(len_doc,i)
        mat.append(vec)
        
    return np.asarray(mat)

print ("\nMATRIX:")
print (get_matrix(doc1))


values:  ['can', 'eat', 'i', 'pizza', 'the']

integer encoded:  [0, 2, 1, 4, 3]

MATRIX:
[[1 0 0 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]]


### Khai phá dữ liệu text (Text Mining)

#### 2.Khái niệm Bag-of-Words

Là kỹ thuật chia văn bản thành các tổ hợp từ khác nhau (bằng phương pháp tokenize). Cách chia phổ biến là mỗi câu thành 1 văn bản (bag) và mỗi văn bản được chia thành từ (word). Dựa vào đó có thể đo lường mức độ xuất hiện của các từ trong văn bản và xây dựng mối liên hệ giữa ngữ cảnh và các từ. 

Hai yếu tố:
1. Từ điển của các từ được sử dụng
2. Mức độ xuất hiện của các từ trong từ điển
*Mỗi từ hay token được gọi là một `gram`*


In [64]:
sentences = [
    'It was the best of times',
    'It was the worst of times',
    'It was the age of wisdom',
    'It was the age of foolishness'
]
sentences

['It was the best of times',
 'It was the worst of times',
 'It was the age of wisdom',
 'It was the age of foolishness']

In [65]:
#['It', 'was', 'the', 'best', 'of', 'times', 'worst', 'age', 'wisdom', 'foolishness'] #Vector từ điển

In [66]:
#It was the best of times :	 [1, 1, 1, 1, 1, 1, 0, 0, 0, 0]
#It was the worst of times :	 [1, 1, 1, 0, 1, 1, 1, 0, 0, 0]
#It was the age of wisdom :	 [1, 1, 1, 0, 1, 0, 0, 1, 1, 0]
#It was the age of foolishness :	 [1, 1, 1, 0, 1, 0, 0, 1, 0, 1]

In [67]:
dictionary = []                          #Thêm dần vào từ điển
for sent in sentences:
    words = nltk.word_tokenize(sent)
    for w in words:
        if w not in dictionary:
            dictionary.append(w)
print(dictionary)

['It', 'was', 'the', 'best', 'of', 'times', 'worst', 'age', 'wisdom', 'foolishness']


In [68]:
for sent in sentences:
    vec = [1 if w in sent else 0 for w in dictionary]
    print(sent, ':\t', vec)

It was the best of times :	 [1, 1, 1, 1, 1, 1, 0, 0, 0, 0]
It was the worst of times :	 [1, 1, 1, 0, 1, 1, 1, 0, 0, 0]
It was the age of wisdom :	 [1, 1, 1, 0, 1, 0, 0, 1, 1, 0]
It was the age of foolishness :	 [1, 1, 1, 0, 1, 0, 0, 1, 0, 1]


#### 3.TF-IDF (Term frequency-Inverse Document frequency)

Ngữ cảnh: I am very angry ->"very angry" Tập trung vào cách từ mang nhiều thông tin

Đơn vị đo thông tin trong machine learnning: entropy 

Đo lường tần suất ***hợp lý*** một từ (hay token) xuất hiện trong văn bản. Tần suất này được tính bằng: Mức độ xuất hiện của từ trong văn bản chia cho tỉ lệ văn bản mà từ đó xuất hiện trên tổng tất cả số lượng văn bản.

Ví dụ: đối với như `what` hay `the`, các từ này xuất hiện rất nhiều tuy nhiên ko mang nhiều ý nghĩa nên cần có phương pháp loại trừ các từ này ra khỏi mô hình. Vì vậy ngoài tính toán mức độ xuất hiện của các từ trong văn bản, tuy nhiên nếu văn bản nào cũng xuất hiện từ này (hoặc đơn giản là rất nhiều > 90%) thì các từ này sẽ bị loại ra.

$$ tf-idf(t, d, D)  = tf(t, d) \dot idf(t, D)$$

> `t`: từ (word hay token)
 
> `d`: văn bản (document)
 
> `D`: tệp các văn bản (documents)

trong đó:

$$ tf(t, d) = \log(1 + freq(t, d)) $$
$$ idf(t, D) = \log \left( \dfrac{N}{count(d \in D: t \in d)} \right)$$

In [70]:
# !pip install gensim

In [71]:
import gensim
from gensim import corpora, models
from gensim.utils import simple_preprocess


/opt/anaconda3/envs/anthony/lib/python3.7/site-packages/gensim/similarities/__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)


In [72]:
import gensim
from gensim import corpora, models
from gensim.utils import simple_preprocess

tokenized = [simple_preprocess(sent) for doc in sentences]
dictionary = corpora.Dictionary()
BoW_corpus = [dictionary.doc2bow(doc, allow_update=True) for doc in tokenized]

for doc in BoW_corpus:
    print([[dictionary[id], freq] for id, freq in doc])

tfidf = models.TfidfModel(BoW_corpus, smartirs='ntc')
for doc in tfidf[BoW_corpus]:
    print([[dictionary[id], np.around(freq)] for id, freq in doc])

[['age', 1], ['foolishness', 1], ['it', 1], ['of', 1], ['the', 1], ['was', 1]]
[['age', 1], ['foolishness', 1], ['it', 1], ['of', 1], ['the', 1], ['was', 1]]
[['age', 1], ['foolishness', 1], ['it', 1], ['of', 1], ['the', 1], ['was', 1]]
[['age', 1], ['foolishness', 1], ['it', 1], ['of', 1], ['the', 1], ['was', 1]]
[['age', 0.0], ['foolishness', 0.0], ['it', 0.0], ['of', 0.0], ['the', 0.0], ['was', 0.0]]
[['age', 0.0], ['foolishness', 0.0], ['it', 0.0], ['of', 0.0], ['the', 0.0], ['was', 0.0]]
[['age', 0.0], ['foolishness', 0.0], ['it', 0.0], ['of', 0.0], ['the', 0.0], ['was', 0.0]]
[['age', 0.0], ['foolishness', 0.0], ['it', 0.0], ['of', 0.0], ['the', 0.0], ['was', 0.0]]


In [73]:
tokenized = [simple_preprocess(sent) for sent in sentences]
tokenized

[['it', 'was', 'the', 'best', 'of', 'times'],
 ['it', 'was', 'the', 'worst', 'of', 'times'],
 ['it', 'was', 'the', 'age', 'of', 'wisdom'],
 ['it', 'was', 'the', 'age', 'of', 'foolishness']]

In [74]:
dictionary = corpora.Dictionary()
bow_corpus = [dictionary.doc2bow(doc, allow_update=True) for doc in tokenized]
bow_corpus

[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1)],
 [(1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1)],
 [(1, 1), (2, 1), (3, 1), (5, 1), (7, 1), (8, 1)],
 [(1, 1), (2, 1), (3, 1), (5, 1), (7, 1), (9, 1)]]

In [75]:
for doc in bow_corpus:
    print([[dictionary[id], freq] for id, freq in doc])

[['best', 1], ['it', 1], ['of', 1], ['the', 1], ['times', 1], ['was', 1]]
[['it', 1], ['of', 1], ['the', 1], ['times', 1], ['was', 1], ['worst', 1]]
[['it', 1], ['of', 1], ['the', 1], ['was', 1], ['age', 1], ['wisdom', 1]]
[['it', 1], ['of', 1], ['the', 1], ['was', 1], ['age', 1], ['foolishness', 1]]


In [76]:
tfidf = models.TfidfModel(bow_corpus, smartirs='ntc')
tfidf

In [77]:
for doc in tfidf[bow_corpus]:
    print([[dictionary[id], freq] for id, freq in doc])

[['best', 0.8448462391634638], ['it', 0.11713529839512135], ['of', 0.11713529839512135], ['the', 0.11713529839512135], ['times', 0.48099076877929264], ['was', 0.11713529839512135]]
[['it', 0.11713529839512132], ['of', 0.11713529839512132], ['the', 0.11713529839512132], ['times', 0.48099076877929253], ['was', 0.11713529839512132], ['worst', 0.8448462391634637]]
[['it', 0.11713529839512132], ['of', 0.11713529839512132], ['the', 0.11713529839512132], ['was', 0.11713529839512132], ['age', 0.48099076877929253], ['wisdom', 0.8448462391634637]]
[['it', 0.11713529839512132], ['of', 0.11713529839512132], ['the', 0.11713529839512132], ['was', 0.11713529839512132], ['age', 0.48099076877929253], ['foolishness', 0.8448462391634637]]


In [78]:
dictionary = corpora.Dictionary()
tokenized = [doc.split(' ') for doc in data['corpus']]
bow_corpus = [dictionary.doc2bow(doc, allow_update=True) for doc in tokenized]

model = models.TfidfModel(bow_corpus)
[[dictionary[id], freq] for id, freq in model[bow_corpus[0]][:10]]

[['biện_pháp', 0.041056865547833686],
 ['bán_lẻ', 0.04908556240345798],
 ['bên', 0.022150442731134225],
 ['bùi', 0.07118245725073921],
 ['bùng_phát', 0.04460812603722285],
 ['bảo_vệ', 0.04995756609294067],
 ['bối_cảnh', 0.034662574749689465],
 ['bội_chi', 0.1006266484130534],
 ['ca', 0.060608811632763285],
 ['chi', 0.04908556240345798]]

In [79]:
dictionary[0]

'biện_pháp'

#### Mô hình Word2vec


*"Word2Vec was developed at Google by Tomas Mikolov, et al. and uses Neural Networks to learn word embeddings. The beauty with word2vec is that the vectors are learned by understanding the context in which words appear. The result is vectors in which words with similar meanings end up with a similar numerical representation."*

**One-hot-encoding**

All word are treated equal

![](https://i2.wp.com/insightbot.blob.core.windows.net/blogimagecontainer/b3c56245-db43-48ab-b652-9ba03f4d9900.jpg?ssl=1)

**Word2Vec**

Word with similar numeric value are similar in meaning

![](https://i1.wp.com/insightbot.blob.core.windows.net/blogimagecontainer/8cbfc874-3ba3-46c8-ab68-2711812ecbf1.jpg?ssl=1)

Hai loại mô hình Word2Vec: **CBOW** (Continuous Bag-of-Word) và **Skip-Gram**

Continuous Bag of Words (CBOW): *nhìn hình (ngữ cảnh) đoán chữ*

Ngược lại, Skip-Gram: *nhìn chữ đoán hình (ngữ cảnh)*

![](https://i0.wp.com/insightbot.blob.core.windows.net/blogimagecontainer/7938152f-71c8-4f28-9c25-06735e6e2b67.jpg?ssl=1)

In [80]:
from gensim.models import Word2Vec

In [81]:
word2vec = Word2Vec(doc_tokenized, min_count=5, sg=0) # 1 == skipgram


NameError: name 'doc_tokenized' is not defined

In [ ]:
print(tokenized[:1][0:100])

In [ ]:
vocabulary = word2vec.wv.key_to_index
print(pd.Series(vocabulary))

In [ ]:
v1 = word2vec.wv['bùng_phát']
v1

In [ ]:
sim_words = word2vec.wv.most_similar('bùng_phát')
sim_words

**Skip-gram**

Window Size defines how many words before and after the target word will be used as context, typically a Window Size is 5. 
![](https://i2.wp.com/insightbot.blob.core.windows.net/blogimagecontainer/a8066c1d-c532-4549-bb24-19dfea5eb178_med.jpg?ssl=1)

Using a window size of 2 the input pairs for training on w(4) royal would be:
![](https://israelg99.github.io/images/2017-03-23-Word2Vec-Explained/training_data.png)

In [ ]:
word2vec = Word2Vec(doc_tokenized, min_count=5, sg=1) # 1 == skipgram

In [ ]:
vocabulary = word2vec.wv.key_to_index
print(pd.Series(vocabulary))

In [ ]:
v1 = word2vec.wv['bùng_phát']
v1

In [ ]:
sim_words = word2vec.wv.most_similar('bùng_phát')
sim_words
#Showw the word