# Lecture 09 - Nature Language Processing (NLP) & Text Mining

## Definition - Định nghĩa

## Flow - Quy trình

## Application - Ứng dụng

## Tools & Library

1. Python Nature Language Toolkit (Python NLTK)
2. Gensim/Tensorflow etc.

## Example

### Token hóa dữ liệu text (Text tokenization)

Là quá trình làm sạch và biến đổi dữ liệu text thành dạng sẵn sàng đưa vào mô hình

#### Tiền xử lý dữ liệu text (Text preprocessing)

In [10]:
import numpy as np
import pandas as pd

data = pd.read_json('Lecture_08/data.json')
data

title  \
0    Thủ tướng: Khác với đa số các nước, dư địa chí...   
1    Thống nhất kịch bản tăng trưởng 3-4%, lạm phát...   
2    Đề xuất tăng liều lượng gói kích thích kinh tế...   
3    Thủ tướng: Khác với đa số các nước, dư địa chí...   
4    Tác động từ chính sách tín dụng: BĐS có thể đó...   
..                                                 ...   
871  Việt Nam thành lập Viện nghiên cứu phát triển ...   
872                       Bất động sản chờ lực bật mới   
873  Diễn đàn Bất động sản 2020: Cơ hội mới từ chín...   
874  Thống đốc Lê Minh Hưng: Tín dụng tăng trở lại,...   
875  Sẵn sàng đón nhận dòng vốn đầu tư dịch chuyển ...   

                                               snippet  \
0    (Tổ Quốc) - Với bối cảnh hiện nay, Hội đồng Tư...   
1    Tại cuộc họp Hội đồng Tư vấn chính sách tài ch...   
2    Chuyên gia đề xuất do dịch bệnh Covid-19 còn k...   
3    Với bối cảnh hiện nay, Hội đồng Tư vấn chính s...   
4    Động thái thắt chặt hay nới lỏng của chính sác...   
..                                                 ...   
871  Sáng 2/7, Đại học Quốc gia Thành phố Hồ Chí Mi...   
872  Chịu nhiều khó khăn do tác động từ đại dịch CO...   
873  Diễn đàn Bất động sản 2020: Cơ hội mới từ chín...   
874  Thống đốc Lê Minh Hưng: Tín dụng tăng trở lại,...   
875  Trong 6 tháng, Việt Nam cơ bản thực hiện thành...   

                                               content  
0    Sáng ngày 9/7, Hội đồng Tư vấn chính sách tài ...  
1    Tham dự cuộc họp có Thống đốc NHNN Lê Minh Hưn...  
2    Sáng 9/7, Thủ tướng Nguyễn Xuân Phúc chủ trì h...  
3    Với bối cảnh hiện nay, Hội đồng Tư vấn chính s...  
4    Lời tòa soạn Thị trường bất động sản ngày càng...  
..                                                 ...  
871  Phát biểu tại buổi lễ, PGS.TS Huỳnh Thanh Đạt,...  
872  Nhu cầu thị trường nhà ở của người dân thuộc p...  
873  BVR&MT – Năm 2020, Thị trường bất động sản có ...  
874  Đến ngày 29/6 tín dụng tăng 3,26%, là mức tăng...  
875  Bộ trưởng Bộ Kế hoạch và Đầu tư Nguyễn Chí Dũn...  

[876 rows x 3 columns]

In [34]:
# TODO: Làm sạch dữ liệu chỉ giữ lại dữ liệu bằng chữ
# 1. Nếu là dữ liệu scrapped từ web thì chỉ trích lọc dữ liệu chứ (text only)
# 2. Loại bỏ hyperlink (nếu có)
# 3. Nếu là dữ liệu web thì cần loại bỏ emoji
# 4. Loại bỏ tất cả các dấu (.,\/!@#$%^&*()+_ etc.)
# 5. Loại bỏ tất cả các số
# 6. Loại bỏ các khoảng trắng và đổi text thành lowercase

In [28]:
!pip install bs4

  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1273 sha256=76de452843188b89663e52ca63b724a1e3e836ae7a3642ee28f2d9930c46fd59
  Stored in directory: c:\users\tdoan\appdata\local\pip\cache\wheels\75\78\21\68b124549c9bdc94f822c02fb9aa3578a669843f9767776bca
Successfully built bs4


In [29]:
# 1.
import bs4 

def del_html(text):
    soup = bs4.BeautifulSoup(text)
    return soup.get_text(' ')

In [18]:
# 2.
import re # regular expression

def del_link(text):
    link = r'http[\S]*'
    text = re.sub(link, ' ', str(text))
    return text

In [20]:
!pip install demoji

In [22]:
# 3.
import demoji

def del_emoji(text):
    return demoji.replace(text, '')

In [23]:
# 4.
def del_punctuation(doc):
    pattern = r'[\,\.\/\\\!\@\#\+\"\'\;\)\(\“\”\\\-\:…&><=\-\%\|\^\$\&\)\(\[\]\{\}\?\*\•]'
    record = re.sub(pattern, ' ', doc)
    return re.sub(r'\n', ' ', record)

In [24]:
# 5.
def del_numbers(text):
    return re.sub(r'\d+', ' ', text)

In [25]:
# 6.
def del_space(doc):
    space_pattern = r'\s+'
    return re.sub(space_pattern, ' ', doc.lower())

In [33]:
text = data.iloc[0, 0]
print(text)
for func in [del_html, del_link, del_emoji, del_punctuation, 
             del_numbers, del_space]:
    text = func(text)
    print(func.__name__, ':', text)


Thủ tướng: Khác với đa số các nước, dư địa chính sách tài khóa, tiền tệ của Việt Nam còn khá lớn
del_html : Thủ tướng: Khác với đa số các nước, dư địa chính sách tài khóa, tiền tệ của Việt Nam còn khá lớn
del_link : Thủ tướng: Khác với đa số các nước, dư địa chính sách tài khóa, tiền tệ của Việt Nam còn khá lớn
del_emoji : Thủ tướng: Khác với đa số các nước, dư địa chính sách tài khóa, tiền tệ của Việt Nam còn khá lớn
del_punctuation : Thủ tướng  Khác với đa số các nước  dư địa chính sách tài khóa  tiền tệ của Việt Nam còn khá lớn
del_numbers : Thủ tướng  Khác với đa số các nước  dư địa chính sách tài khóa  tiền tệ của Việt Nam còn khá lớn
del_space : thủ tướng khác với đa số các nước dư địa chính sách tài khóa tiền tệ của việt nam còn khá lớn


#### Chia từ (Word tokenizing) - Tiếng Anh vs Tiếng Việt

In [49]:
# Tiếng Anh

In [40]:
!pip install nltk

In [45]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [72]:
import nltk

sentence = 'A quick brown fox jump over a lazy dog.'
nltk.word_tokenize(sentence)

['A', 'quick', 'brown', 'fox', 'jump', 'over', 'a', 'lazy', 'dog', '.']

In [73]:
nltk.sent_tokenize(sentence)

['A quick brown fox jump over a lazy dog.']

In [74]:
sentences = '''A quick brown fox jump over a lazy dog.
He is the royal king.
'''

[nltk.word_tokenize(i) for i in nltk.sent_tokenize(sentences)]

[['A', 'quick', 'brown', 'fox', 'jump', 'over', 'a', 'lazy', 'dog', '.'],
 ['He', 'is', 'the', 'royal', 'king', '.']]

In [54]:
print(nltk.word_tokenize(text))

['thủ', 'tướng', 'khác', 'với', 'đa', 'số', 'các', 'nước', 'dư', 'địa', 'chính', 'sách', 'tài', 'khóa', 'tiền', 'tệ', 'của', 'việt', 'nam', 'còn', 'khá', 'lớn']


In [50]:
# Tiếng Việt

In [39]:
!pip install pyvi

In [47]:
from pyvi.ViTokenizer import tokenize

tokenize(text)

'thủ_tướng khác với đa_số các nước dư địa_chính_sách tài khóa tiền_tệ của việt nam còn khá lớn'

In [52]:
print(tokenize(text).split())

['thủ_tướng', 'khác', 'với', 'đa_số', 'các', 'nước', 'dư', 'địa_chính_sách', 'tài', 'khóa', 'tiền_tệ', 'của', 'việt', 'nam', 'còn', 'khá', 'lớn']


#### Put together

In [61]:
def clean_text(text):
    text = del_html(text)
    text = del_link(text)
    text = del_numbers(text)
    text = del_emoji(text)
    text = del_punctuation(text)
    text = del_space(text)
    return tokenize(text)

In [69]:
data['corpus'] = data.apply(lambda x: ' '.join(x), axis=1)
data['corpus']

0      Thủ tướng: Khác với đa số các nước, dư địa chí...
1      Thống nhất kịch bản tăng trưởng 3-4%, lạm phát...
2      Đề xuất tăng liều lượng gói kích thích kinh tế...
3      Thủ tướng: Khác với đa số các nước, dư địa chí...
4      Tác động từ chính sách tín dụng: BĐS có thể đó...
                             ...                        
871    Việt Nam thành lập Viện nghiên cứu phát triển ...
872    Bất động sản chờ lực bật mới Chịu nhiều khó kh...
873    Diễn đàn Bất động sản 2020: Cơ hội mới từ chín...
874    Thống đốc Lê Minh Hưng: Tín dụng tăng trở lại,...
875    Sẵn sàng đón nhận dòng vốn đầu tư dịch chuyển ...
Name: corpus, Length: 876, dtype: object

In [70]:
data['corpus'] = data['joined'].apply(clean_text)
data['corpus']

0      thủ_tướng khác với đa_số các nước dư địa_chính...
1      thống_nhất kịch_bản tăng_trưởng lạm_phát dưới ...
2      đề_xuất tăng liều_lượng gói kích_thích kinh_tế...
3      thủ_tướng khác với đa_số các nước dư địa_chính...
4      tác_động từ chính_sách tín_dụng bđs có_thể đón...
                             ...                        
871    việt nam thành_lập viện nghiên_cứu phát_triển ...
872    bất_động_sản chờ lực bật mới chịu nhiều khó_kh...
873    diễn_đàn bất_động_sản cơ_hội mới từ chính_sách...
874    thống_đốc lê minh hưng tín_dụng tăng trở_lại n...
875    sẵn_sàng đón_nhận dòng vốn đầu_tư dịch_chuyển ...
Name: corpus, Length: 876, dtype: object

In [79]:
data.loc[0, 'corpus'][:500]

'thủ_tướng khác với đa_số các nước dư địa_chính_sách tài khóa tiền_tệ của việt nam còn khá lớn tổ_quốc với bối_cảnh hiện_nay hội_đồng tư_vấn chính_sách tài_chính tiền_tệ quốc_gia thống_nhất kịch_bản tăng_trưởng từ kiểm_soát lạm_phát dưới năm và đầu tăng_trưởng tín_dụng trên chủ_trương tăng thêm bội_chi ngân_sách nợ công khoảng gdp sáng ngày hội_đồng tư_vấn chính_sách tài_chính tiền_tệ quốc_gia đã họp dưới sự chủ_trì của thủ_tướng nguyễn xuân phúc chủ_tịch hội_đồng dư địa_chính_sách tài khóa tiền_'

### Mã hóa dữ liệu text (Word embedding)

#### One-hot encoding

In [85]:
# Chuyển thành dạng lowercase (nếu chưa)
# tách từ (tokenize), loại bỏ từ trùng lặp (set)
# Sắp xếp theo thứ tự a-z
# Lấy giá trị vị trí
# Chuyển đổi thành vector [0, 1] tương ứng giá trị vị trí

In [84]:
sentence = 'Can I eat the pizza'
sorted(nltk.word_tokenize(sentence.lower()))

['can', 'eat', 'i', 'pizza', 'the']

In [87]:
docs = "Can I eat the Pizza".lower().split()
doc1 = set(docs)
doc1 = sorted(doc1)
print ("\nvalues: ", doc1)

integer_encoded = []
for i in docs:
    v = np.where( np.array(doc1) == i)[0][0]
    integer_encoded.append(v)
print ("\ninteger encoded: ",integer_encoded)

def get_vec(len_doc,word):
    empty_vector = [0] * len_doc
    vect = 0
    find = np.where( np.array(doc1) == word)[0][0]
    empty_vector[find] = 1
    return empty_vector

def get_matrix(doc1):
    mat = []
    len_doc = len(doc1)
    for i in docs:
        vec = get_vec(len_doc,i)
        mat.append(vec)
        
    return np.asarray(mat)

print ("\nMATRIX:")
print (get_matrix(doc1))


values:  ['can', 'eat', 'i', 'pizza', 'the']

integer encoded:  [0, 2, 1, 4, 3]

MATRIX:
[[1 0 0 0 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]]


### Khai phá dữ liệu text (Text Mining)

#### Khái niệm Bag-of-Words

Là kỹ thuật chia văn bản thành các tổ hợp từ khác nhau (bằng phương pháp tokenize). Cách chia phổ biến là mỗi câu thành 1 văn bản (bag) và mỗi văn bản được chia thành từ (word). Dựa vào đó có thể đo lường mức độ xuất hiện của các từ trong văn bản và xây dựng mối liên hệ giữa ngữ cảnh và các từ. 

Hai yếu tố:
1. Từ điển của các từ được sử dụng
2. Mức độ xuất hiện của các từ trong từ điển
*Mỗi từ hay token được gọi là một `gram`*


In [90]:
sentences = [
    'It was the best of times',
    'It was the worst of times',
    'It was the age of wisdom',
    'It was the age of foolishness'
]
sentences

['It was the best of times',
 'It was the worst of times',
 'It was the age of wisdom',
 'It was the age of foolishness']

In [92]:
dictionary = []
for sent in sentences:
    words = nltk.word_tokenize(sent)
    for w in words:
        if w not in dictionary:
            dictionary.append(w)
print(dictionary)

['It', 'was', 'the', 'best', 'of', 'times', 'worst', 'age', 'wisdom', 'foolishness']


In [94]:
for sent in sentences:
    vec = [1 if w in sent else 0 for w in dictionary]
    print(sent, ':\t', vec)

It was the best of times :	 [1, 1, 1, 1, 1, 1, 0, 0, 0, 0]
It was the worst of times :	 [1, 1, 1, 0, 1, 1, 1, 0, 0, 0]
It was the age of wisdom :	 [1, 1, 1, 0, 1, 0, 0, 1, 1, 0]
It was the age of foolishness :	 [1, 1, 1, 0, 1, 0, 0, 1, 0, 1]


#### TF-IDF (Term frequency-Inverse Document frequency)

Đo lường tần suất ***hợp lý*** một từ (hay token) xuất hiện trong văn bản. Tần suất này được tính bằng: Mức độ xuất hiện của từ trong văn bản chia cho tỉ lệ văn bản mà từ đó xuất hiện trên tổng tất cả số lượng văn bản.

Ví dụ: đối với như `what` hay `the`, các từ này xuất hiện rất nhiều tuy nhiên ko mang nhiều ý nghĩa nên cần có phương pháp loại trừ các từ này ra khỏi mô hình. Vì vậy ngoài tính toán mức độ xuất hiện của các từ trong văn bản, tuy nhiên nếu văn bản nào cũng xuất hiện từ này (hoặc đơn giản là rất nhiều > 90%) thì các từ này sẽ bị loại ra.

$$ tf-idf(t, d, D)  = tf(t, d) \dot idf(t, D)$$

> `t`: từ (word hay token)
 
> `d`: văn bản (document)
 
> `D`: tệp các văn bản (documents)

trong đó:

$$ tf(t, d) = \log(1 + freq(t, d)) $$
$$ idf(t, D) = \log \left( \dfrac{N}{count(d \in D: t \in d)} \right)$$

In [95]:
!pip install gensim

In [96]:
import gensim
from gensim import corpora, models
from gensim.utils import simple_preprocess

tokenized = [simple_preprocess(sent) for doc in sentences]
dictionary = corpora.Dictionary()
BoW_corpus = [dictionary.doc2bow(doc, allow_update=True) for doc in doc_tokenized]

for doc in BoW_corpus:
    print([[dictionary[id], freq] for id, freq in doc])

tfidf = models.TfidfModel(BoW_corpus, smartirs='ntc')
for doc in tfidf[BoW_corpus]:
    print([[dictionary[id], np.around(freq)] for id, freq in doc])

[['age', 1], ['foolishness', 1], ['it', 1], ['of', 1], ['the', 1], ['was', 1]]
[['age', 1], ['foolishness', 1], ['it', 1], ['of', 1], ['the', 1], ['was', 1]]
[['age', 1], ['foolishness', 1], ['it', 1], ['of', 1], ['the', 1], ['was', 1]]
[['age', 1], ['foolishness', 1], ['it', 1], ['of', 1], ['the', 1], ['was', 1]]
[['age', 0.0], ['foolishness', 0.0], ['it', 0.0], ['of', 0.0], ['the', 0.0], ['was', 0.0]]
[['age', 0.0], ['foolishness', 0.0], ['it', 0.0], ['of', 0.0], ['the', 0.0], ['was', 0.0]]
[['age', 0.0], ['foolishness', 0.0], ['it', 0.0], ['of', 0.0], ['the', 0.0], ['was', 0.0]]
[['age', 0.0], ['foolishness', 0.0], ['it', 0.0], ['of', 0.0], ['the', 0.0], ['was', 0.0]]


c:\users\tdoan\appdata\local\programs\python\python38\lib\site-packages\gensim\similarities\__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)


In [98]:
tokenized = [simple_preprocess(sent) for sent in sentences]
tokenized

[['it', 'was', 'the', 'best', 'of', 'times'],
 ['it', 'was', 'the', 'worst', 'of', 'times'],
 ['it', 'was', 'the', 'age', 'of', 'wisdom'],
 ['it', 'was', 'the', 'age', 'of', 'foolishness']]

In [100]:
dictionary = corpora.Dictionary()
bow_corpus = [dictionary.doc2bow(doc, allow_update=True) for doc in tokenized]
bow_corpus

[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1)],
 [(1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1)],
 [(1, 1), (2, 1), (3, 1), (5, 1), (7, 1), (8, 1)],
 [(1, 1), (2, 1), (3, 1), (5, 1), (7, 1), (9, 1)]]

In [101]:
for doc in bow_corpus:
    print([[dictionary[id], freq] for id, freq in doc])

[['best', 1], ['it', 1], ['of', 1], ['the', 1], ['times', 1], ['was', 1]]
[['it', 1], ['of', 1], ['the', 1], ['times', 1], ['was', 1], ['worst', 1]]
[['it', 1], ['of', 1], ['the', 1], ['was', 1], ['age', 1], ['wisdom', 1]]
[['it', 1], ['of', 1], ['the', 1], ['was', 1], ['age', 1], ['foolishness', 1]]


In [102]:
tfidf = models.TfidfModel(bow_corpus, smartirs='ntc')
tfidf

In [104]:
for doc in tfidf[bow_corpus]:
    print([[dictionary[id], freq] for id, freq in doc])

[['best', 0.8448462391634638], ['it', 0.11713529839512135], ['of', 0.11713529839512135], ['the', 0.11713529839512135], ['times', 0.48099076877929264], ['was', 0.11713529839512135]]
[['it', 0.11713529839512132], ['of', 0.11713529839512132], ['the', 0.11713529839512132], ['times', 0.48099076877929253], ['was', 0.11713529839512132], ['worst', 0.8448462391634637]]
[['it', 0.11713529839512132], ['of', 0.11713529839512132], ['the', 0.11713529839512132], ['was', 0.11713529839512132], ['age', 0.48099076877929253], ['wisdom', 0.8448462391634637]]
[['it', 0.11713529839512132], ['of', 0.11713529839512132], ['the', 0.11713529839512132], ['was', 0.11713529839512132], ['age', 0.48099076877929253], ['foolishness', 0.8448462391634637]]


In [111]:
dictionary = corpora.Dictionary()
doc_tokenized = [doc.split(' ') for doc in data['corpus']]
BoW_corpus = [dictionary.doc2bow(doc, allow_update=True) for doc in doc_tokenized]

model = models.TfidfModel(BoW_corpus)
[[dictionary[id], freq] for id, freq in model[BoW_corpus[0]][:10]]

[['biện_pháp', 0.0412356814796833],
 ['bán_lẻ', 0.04929934590749365],
 ['bên', 0.022246915075162407],
 ['bùi', 0.0714924798804455],
 ['bùng_phát', 0.04571307724402378],
 ['bảo_vệ', 0.053548195600883426],
 ['bối_cảnh', 0.03481354147648335],
 ['bội_chi', 0.10106491002082081],
 ['ca', 0.06087278261510201],
 ['chi', 0.04929934590749365]]

#### Mô hình Word2vec


*"Word2Vec was developed at Google by Tomas Mikolov, et al. and uses Neural Networks to learn word embeddings. The beauty with word2vec is that the vectors are learned by understanding the context in which words appear. The result is vectors in which words with similar meanings end up with a similar numerical representation."*

**One-hot-encoding**

All word are treated equal

![](https://i2.wp.com/insightbot.blob.core.windows.net/blogimagecontainer/b3c56245-db43-48ab-b652-9ba03f4d9900.jpg?ssl=1)

**Word2Vec**

Word with similar numeric value are similar in meaning

![](https://i1.wp.com/insightbot.blob.core.windows.net/blogimagecontainer/8cbfc874-3ba3-46c8-ab68-2711812ecbf1.jpg?ssl=1)

Hai loại mô hình Word2Vec: **CBOW** (Continuous Bag-of-Word) và **Skip-Gram**

Continuous Bag of Words (CBOW): *nhìn hình (ngữ cảnh) đoán chữ*

Ngược lại, Skip-Gram: *nhìn chữ đoán hình (ngữ cảnh)*

![](https://i0.wp.com/insightbot.blob.core.windows.net/blogimagecontainer/7938152f-71c8-4f28-9c25-06735e6e2b67.jpg?ssl=1)

In [113]:
from gensim.models import Word2Vec

In [140]:
word2vec = Word2Vec(doc_tokenized, min_count=5, sg=0) # 1 == skipgram

In [141]:
vocabulary = word2vec.wv.key_to_index
print(pd.Series(vocabulary))

các                           0
và                            1
trong                         2
kinh_tế                       3
của                           4
                           ... 
thitruongtaichinhtiente    3411
giải_đáp                   3412
mùi                        3413
kịch_bản_chính_phủ         3414
đòn_bẩy                    3415
Length: 3416, dtype: int64


In [142]:
v1 = word2vec.wv['tổ_quốc']
v1

array([-1.82342157e-01,  3.83873552e-01, -1.44534394e-01,  7.65922964e-02,
        3.79345298e-01, -8.65793601e-02,  6.54608086e-02,  3.48696619e-01,
       -7.62954503e-02,  2.48731732e-01, -2.99366474e-01,  1.77202493e-01,
        1.85716361e-01,  3.42042819e-02,  3.39961052e-02,  3.26030195e-01,
        2.39822686e-01, -1.57269493e-01,  1.29891410e-01, -7.24578351e-02,
       -3.46942693e-02,  1.01858690e-01,  1.10700741e-01, -3.27607900e-01,
       -1.59938946e-01,  1.40665993e-01, -7.28769675e-02, -9.45709646e-02,
       -8.08669925e-02,  2.94243246e-01,  2.58075923e-01,  7.69154653e-02,
       -1.48420945e-01, -5.89549877e-02, -1.42466366e-01,  1.82856530e-01,
       -1.44799575e-01, -3.64023000e-02, -1.14192717e-01, -2.64315218e-01,
        1.23347327e-01, -2.37349595e-05,  2.43588090e-01, -1.66029021e-01,
       -2.81853884e-01,  4.55741175e-02, -2.96600282e-01, -1.35715514e-01,
       -1.56706020e-01, -4.54942659e-02,  1.19437270e-01,  1.32989526e-01,
        7.24774823e-02, -

In [143]:
sim_words = word2vec.wv.most_similar('kéo_dài')
sim_words

[('ngắn', 0.6528961658477783),
 ('điểm_nóng', 0.5696249008178711),
 ('khiếu_kiện', 0.5383105278015137),
 ('cứu', 0.5162107348442078),
 ('kết_thúc', 0.4972623288631439),
 ('nó', 0.48638781905174255),
 ('mạnh_tay', 0.4734785854816437),
 ('đối_phó', 0.4685332179069519),
 ('khó', 0.4460851550102234),
 ('tồn_tại', 0.44549649953842163)]

**Skip-gram**

Window Size defines how many words before and after the target word will be used as context, typically a Window Size is 5. 
![](https://i2.wp.com/insightbot.blob.core.windows.net/blogimagecontainer/a8066c1d-c532-4549-bb24-19dfea5eb178_med.jpg?ssl=1)

Using a window size of 2 the input pairs for training on w(4) royal would be:
![](https://israelg99.github.io/images/2017-03-23-Word2Vec-Explained/training_data.png)

In [144]:
word2vec = Word2Vec(doc_tokenized, min_count=5, sg=1) # 1 == skipgram

In [145]:
vocabulary = word2vec.wv.key_to_index
print(pd.Series(vocabulary))

các                           0
và                            1
trong                         2
kinh_tế                       3
của                           4
                           ... 
thitruongtaichinhtiente    3411
giải_đáp                   3412
mùi                        3413
kịch_bản_chính_phủ         3414
đòn_bẩy                    3415
Length: 3416, dtype: int64


In [146]:
v1 = word2vec.wv['tổ_quốc']
v1

array([-0.16557786,  0.5547214 , -0.0700129 ,  0.1856907 ,  0.31796294,
       -0.10810167, -0.23590812,  0.2633175 , -0.08135381,  0.20161693,
       -0.28856915,  0.14334552, -0.01961311, -0.00207503,  0.30414698,
        0.40060127,  0.13037017, -0.34005964,  0.09793479, -0.07910369,
       -0.01611584, -0.02239303,  0.13974565, -0.17828597, -0.05571358,
        0.1735891 , -0.05605118, -0.02122932, -0.00363449,  0.11936511,
        0.06295639,  0.2585639 , -0.19181433,  0.15629879, -0.16519181,
        0.5765332 , -0.25817135, -0.3060833 , -0.014099  , -0.40463704,
        0.07919086, -0.04855295,  0.51362985,  0.04634253, -0.34635028,
        0.23560238, -0.16420652, -0.24368556, -0.2738499 , -0.03009408,
        0.14965206, -0.3480504 ,  0.16400012, -0.07400417, -0.13233477,
       -0.3096474 , -0.0051062 ,  0.2159299 , -0.4862298 , -0.29382944,
        0.6075605 ,  0.00283417,  0.05742108,  0.24343829, -0.10527484,
       -0.22211182, -0.02327074,  0.1256666 ,  0.17983614,  0.13

In [147]:
sim_words = word2vec.wv.most_similar('kéo_dài')
sim_words

[('ngắn', 0.6494366526603699),
 ('khiếu_kiện', 0.6469146013259888),
 ('công_cuộc', 0.6077184677124023),
 ('điểm_nóng', 0.5989739298820496),
 ('tiêu_tan', 0.5805805325508118),
 ('tạm_ứng', 0.5127071142196655),
 ('phát_huy_hiệu_quả', 0.5120418667793274),
 ('chăn', 0.506695568561554),
 ('dẫu', 0.5055784583091736),
 ('chờ_đợi', 0.5048704147338867)]